#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>

#include "app_shared.h"

enum app_command parse_command(const char *cmd)
{
	if (!strcmp(cmd, "calibrate"))
		return CMD_CALIBRATE;
	if (!strcmp(cmd, "waveform"))
		return CMD_WAVEFORM;
	if (!strcmp(cmd, "bintest"))
		return CMD_BINTEST;
	if (!strcmp(cmd, "stream"))
		return CMD_STREAM;
	if (!strcmp(cmd, "wav"))
		return CMD_WAV;
	if (!strcmp(cmd, "wavol"))
		return CMD_WAVOL;
	if (!strcmp(cmd, "music"))
		return CMD_MUSIC;
	if (!strcmp(cmd, "musicol"))
		return CMD_MUSICOL;
	if (!strcmp(cmd, "samples"))
		return CMD_SAMPLES;
	if (!strcmp(cmd, "streambin"))
		return CMD_STREAMBIN;
	if (!strcmp(cmd, "status"))
		return CMD_STATUS;
	if (!strcmp(cmd, "interval"))
		return CMD_INTERVAL;
	if (!strcmp(cmd, "localmode"))
		return CMD_LOCALMODE;
	if (!strcmp(cmd, "syncmode"))
		return CMD_SYNCMODE;
	return CMD_INVALID;
}

int parse_device_arg(const char *arg)
{
	int device;

	device = atoi(arg);
	if (device != 1 && device != 2)
		return -1;

	return device;
}

int parse_sync_mode_arg(const char *arg)
{
	if (!strcmp(arg, "sync"))
		return 1;
	if (!strcmp(arg, "local"))
		return 0;
	return -1;
}

int parse_int_arg(const char *arg, int *value)
{
	char *end;
	long parsed;

	parsed = strtol(arg, &end, 10);
	if (end == arg || *end != '\0')
		return -1;
	*value = (int)parsed;
	return 0;
}

int configure_device(int fd, int mode, int trigger, const char *name)
{
	int ret;

	ret = ioctl(fd, DRV2624_CHANGE_MODE, &mode);
	if (ret < 0) {
		perror(name);
		return ret;
	}

	ret = ioctl(fd, DRV2624_CHANGE_TRIGGERFUNC, &trigger);
	if (ret < 0) {
		perror(name);
		return ret;
	}

	return 0;
}

int configure_local_mode(int fd, int mode, const char *name)
{
	int ret;

	ret = ioctl(fd, DRV2624_CONFIG_LOCAL_MODE, &mode);
	if (ret < 0) {
		perror(name);
		return ret;
	}

	return 0;
}

int configure_local_open_loop_mode(int fd, int mode, int ol_frequency,
				   const char *name)
{
	struct drv2624_openloop_config config;
	int ret;

	config.mode = mode;
	config.ol_frequency = ol_frequency;
	ret = ioctl(fd, DRV2624_CONFIG_LOCAL_OPEN_LOOP_MODE, &config);
	if (ret < 0) {
		perror(name);
		return ret;
	}

	return 0;
}

int configure_sync_open_loop_mode(int fd, int mode, int ol_frequency,
				  const char *name)
{
	struct drv2624_openloop_config config;
	int ret;

	config.mode = mode;
	config.ol_frequency = ol_frequency;
	ret = ioctl(fd, DRV2624_CONFIG_SYNC_OPEN_LOOP_MODE, &config);
	if (ret < 0) {
		perror(name);
		return ret;
	}

	return 0;
}

int configure_sync_close_loop_mode(int fd, int mode, const char *name)
{
	int ret;

	ret = ioctl(fd, DRV2624_CONFIG_SYNC_CLOSE_LOOP_MODE, &mode);
	if (ret < 0) {
		perror(name);
		return ret;
	}

	return 0;
}

int get_status_value(int fd, int *status)
{
	int ret;

	ret = ioctl(fd, DRV2624_GET_STATUS, status);
	if (ret < 0)
		perror("ioctl DRV2624_GET_STATUS");
	return ret;
}

int get_playback_interval_value(int fd, int *interval_ms)
{
	int ret;

	ret = ioctl(fd, DRV2624_GET_PLAYBACK_INTERVAL, interval_ms);
	if (ret < 0)
		perror("ioctl DRV2624_GET_PLAYBACK_INTERVAL");
	return ret;
}

int set_playback_interval_value(int fd, int interval_ms, const char *name)
{
	int ret;

	ret = ioctl(fd, DRV2624_SET_PLAYBACK_INTERVAL, &interval_ms);
	if (ret < 0)
		perror(name);
	return ret;
}

void print_usage(const char *prog)
{
	fprintf(stderr,
		"usage:\n"
		"  %s calibrate\n"
		"  %s waveform <device> <effect>\n"
		"  %s bintest <device> <effect[:loop]> [effect[:loop] ...]\n"
		"  %s stream <device> <level> [local|sync]\n"
		"  %s wav <device> <file.wav> [local|sync] [max_amp] [target_rate_hz]\n"
		"  %s wavol <device> <file.wav> [max_amp] [target_rate_hz] [ol_freq_hz]\n"
		"  %s music <device> [local|sync]\n"
		"  %s musicol <device> [ol_freq_hz]\n"
		"  %s samples <device> [local|sync]\n"
		"  %s streambin <device> <music.bin|samples.bin> [local|sync]\n"
		"  %s status <device>\n"
		"  %s interval <device> [1|5]\n"
		"  %s localmode <device> <mode>\n"
		"  %s syncmode <device> <mode>\n"
		"device: 1 or 2\n"
		"waveform effect: use effect ids from builtin waveform or drv2624.bin\n"
		"bintest effect: use effect ids from drv2624.bin\n"
		"stream level: -128..127, default mode is local\n"
		"wav: uncompressed PCM wav (8-bit/16-bit, mono/stereo)\n"
		"     max_amp: 1..127, default 80\n"
		"     target_rate_hz: optional, 0 or omitted means use source wav rate\n"
		"     ol_freq_hz: optional for wavol, 0 keeps driver default\n"
		"music: play /userdata/music.bin in closed-loop mode\n"
		"musicol: play /userdata/music.bin in local open-loop mode\n"
		"samples: play /userdata/samples.bin\n"
		"streambin: precompiled binary stream generated by Python scripts\n"
		"status: read raw STATUS register value (clears sticky bits on read)\n"
		"interval: get or set playback interval in milliseconds (1 or 5)\n"
		"mode: 0=RTP 1=WAVEFORM 2=DIAGNOSTICS 3=CALIBRATION\n",
		prog, prog, prog, prog, prog, prog, prog, prog, prog, prog, prog, prog,
		prog, prog);
}
